nutch:
  image: smartive/nutch:es-5
  ports:
    - "8080:8080"
    - "8081:8081"
  links:
    - "mongodb:mongodb"
    - "elasticsearch:elasticsearch"
  volumes:
    - "./config/ivy.xml:/root/nutch/ivy/ivy.xml"
    - "./config/nutch-site.xml:/root/nutch/conf/nutch-site.xml"
    - "./config/regex-urlfilter.txt:/root/nutch/conf/regex-urlfilter.txt"
    - "./crawldata:/root/crawldata"
mongodb:
  image: mongo
  ports:
    - "27020:27017"
  volumes:
    - "./data/mongo:/data/db"
elasticsearch:
  image: elasticsearch:5.4
  ports:
    - "9200:9200"
    - "9300:9300"
